#version : '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  user-service:
    build: ./user-service
    container_name: user-service
    ports: 
      - "5001:5001"
    depends_on:
      - mongodb

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"


  task-service:
    build: ./task-service
    container_name: task-service
    ports:
      - "5002:5002"
    depends_on:
      - mongodb
      - user-service 
      - rabbitmq

     
  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "5003:5003"
    depends_on:
      - mongodb
      - user-service
      - task-service
      - rabbitmq


volumes:
  mongo_data: