#version : '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  user-service:
    build: ./user-service
    container_name: user-service
    ports: 
      - "5001:5001"
    depends_on:
      - mongodb

  task-service:
    build: ./task-service
    container_name: task-service
    ports:
      - "5002:5002"
    depends_on:
      - mongodb
      - user-service 
     


volumes:
  mongo_data: